version = "v1"
brand = "tasi"
model = "ta612c"
temperature_unit = "C" # C or F
alarms = [160, 170, 180, 190, 200]

[serial]
    port      = "COM5"
    baud_rate = 9600
    data_bits = 8
    parity    = "none"
    stop_bits = 1

    [serial.ta612c]

        [[serial.ta612c.channel]]
            channel_id  = "BT"
            label       = "bean temp"
            color       = "#191970"
            ror_color   = "#4169E1" # BT only

        [[serial.ta612c.channel]]
            channel_id  = "ET"
            label       = "exhaust temp"
            color       = "#ff0000"

[[manual_channel]]
    channel_id  = "gas"
    label       = "Gas"
    unit        = "mmHg"
    color       = "#007f00"
    min         = 0
    max         = 100
    step        = 10        
    default_value = 20

[[manual_channel]]
    channel_id  = "airflow"
    label       = "Airflow"
    unit        = "Pa"
    color       = "#007f00"
    min         = 26
    max         = 40
    step        = 1         
    default_value = 32

# you CANNOT write top level keys after array of tables