version = "v1"
brand   = "kapok"
model   = "501"
temperature_unit = "C" # C or F
alarms = [160, 170, 180, 190, 200]

[serial]
    port      = "COM4"
    baud_rate = 9600
    data_bits = 8
    parity    = "none"
    stop_bits = 1

    [serial.modbus]
        # modbus-ascii, modbus-rtu
        protocol = "modbus-ascii"

        [[serial.modbus.slave]]
            channel_id  = "ET"
            label       = "exhaust temp"
            color       = "#ff0000"
            id          = 1
            function    = 3
            registry    = 18176     # = 4700h
            divisor     = 10        # 1, 10, 100
            decode_type = "u16"     # u16, u32, i16, i32, f32

        [[serial.modbus.slave]]
            channel_id  = "BT"
            label       = "bean temp"
            color       = "#191970"
            ror_color   = "#4169E1" # BT only
            id          = 2
            function    = 3
            registry    = 18176     # = 4700h
            divisor     = 10        # 1, 10, 100
            decode_type = "u16"     # u16, u32, i16, i32, f32

        [[serial.modbus.slave]]
            channel_id  = "inlet"
            label       = "inlet temp"
            color       = "#2E8B57"
            id          = 3
            function    = 3
            registry    = 18176     # = 4700h
            divisor     = 10        # 1, 10, 100
            decode_type = "u16"     # u16, u32, i16, i32, f32

[[manual_channel]]
    channel_id  = "gas"
    label       = "Gas"
    unit        = "mmHg"
    color       = "#007f00"
    min         = 0
    max         = 100
    step        = 10        
    default_value     = 20

[[manual_channel]]
    channel_id  = "airflow"
    label       = "Airflow"
    unit        = "Pa"
    color       = "#007f00"
    min         = 28
    max         = 42
    step        = 1         
    default_value     = 32

# you CANNOT write top level keys after array of tables